#!/bin/bash
if [ -z $1 ]; then
	echo "usage: pigsh 0"
	echo "to connect to /dev/ttyACM0"
	exit
fi
echo " " > /dev/ttyACM$1
while true; do
read -e -p "pigsh>" shinput
	history -s "$shinput"
	echo $shinput > /dev/ttyACM$1
done
